### ISSUE TITLE
Documenting R dependencies

### ISSUE THREAD

**Issue by kmkostka** [ohdsi-studies/Covid19CharacterizationCharybdis#2]
We need to enumerate the packages that this study needs to think. This is important for people who can't call out to GitHub and need to download things manually.

**Comment by anthonysena** [comment]
I've updated the DESCRIPTION file in the repo so it should now cover all dependencies. We should also add to the `extras\CodeToRun.R` the install commands for each package to make it easier.

**Comment by anthonysena** [comment]
#73 will provide an explicit list of these in the renv.lock file and also allow for the proper dependency management.
