### ISSUE TITLE
CUIMC issue trying to execute this.

### ISSUE THREAD

**Issue by msuchard** [ohdsi-studies/Covid19CharacterizationCharybdis#21]
https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/2a0307553d270d849992b475ab12a7d33e2e8bf8/extras/CodeToRun.R#L176

@anthonysena -- did you mean
`cohortGroups = list(cohortGroup = c("covid", "influenza")` here?  Otherwise this generates an error in `runStudy`?

**Comment by pbr6cornell** [comment]
That should be uncommented in order to run the package against both covid and influenza cohorts.  If the database only have COVID cohorts, then delete 'influenza'.  If a database only have 'influenza' cohorts, then delete 'covid'.

**Comment by pbr6cornell** [comment]
See comment here: https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/2a0307553d270d849992b475ab12a7d33e2e8bf8/extras/CodeToRun.R#L133

**Comment by msuchard** [comment]
Nope.  Does not currently work as written for CUIMC.   Requires a sub-field called `cohortGroup`.  Please fix either here or in `runStudy`.

**Comment by anthonysena** [comment]
@msuchard sorry for that bug - specifying a vector of cohort group names should now function as expected. Thanks!
