### ISSUE TITLE
CohortDiagnostics ff object error

### ISSUE THREAD

**Issue by AEW0330** [ohdsi-studies/Covid19CharacterizationCharybdis#26]
These parts of CohortDiagnostics code ran successfully: Creating cohorts in incremental mode; Saving database metadata; Counting cohorts; Fetching included source concepts; Counting codes in concept sets; Finding orphan concepts; Creating time distributions; - Creating time distributions for cohort 126; Constructing features on server.

Then when Fetching data from server was executing, got this error: 
     Error: 'querySql.ffdf' is not an exported object from 'namespace:DatabaseConnector'

Didn't see an error or log file to share

**Comment by gowthamrao** [comment]
Hey Andrew - could you please try re-running after updating
- Cohort Diagnostics
- DatabaseConnector
- FeatureExtraction
- ParallelLogger

Please ensure all dependencies are also updated.
Yesterday we said goodbye to FF and switched to Andromeda.

Maybe that would fix the issue

**Comment by anthonysena** [comment]
@AEW0330 - have you set the `options(fftempdir = fftempdir)` in your code to point to a valid location? Here is where that is done in the CodeToRun.R: https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/master/extras/CodeToRun.R#L72.

The diagnostics should create a subfolder called 'diagnostics' in the `outputFolder` that contains a log file if you'd like to share that. If you don't have that log, there may be a different issue.

**Comment by AEW0330** [comment]
That did the trick. Thanks.
This issue is resolved!
I'll check with Kristin re whether I use the same keyfile as for other COVID study a thon results.
Doesn't look like this script is using ohdsiSharing

Ran into some trouble with displaying results. Do those issues go here or in CohortDiagnostics?
