### ISSUE TITLE
CohortDiagnostics shiny default select options for Cohort Characterization and warnings

### ISSUE THREAD

**Issue by AEW0330** [ohdsi-studies/Covid19CharacterizationCharybdis#30]
Minor UX issue: When first clicking on Cohort Characterization, all cohorts are selected and some proportion numbers are displayed. I'm not sure what they are proportions of. But new users will find it confusing - they are strange numbers not totaling to 1. This warning appears in R: 
_Warning: longer object length is not a multiple of shorter object length_
But deselecting and then selecting a single cohort gives the correct display.

Clicking on Cohort Compare generates other warnings in R
_Warning: Error in : Must subset rows with a valid subscript vector.
i Logical subscripts must match the size of the indexed input.
x Input has size 5161535 but subscript `&...` has size 0.
  119: <Anonymous>_
But results seem correct. 

Amazing tool! Sooo useful. Thanks!

**Comment by anthonysena** [comment]
Hi @AEW0330 - really sorry for the delayed response here. I'm not sure I fully understand this issue - this appears to be an issue with the R Shiny app but I'm unsure if this is what you experienced when running the Cohort Diagnostics viewer or the Charybdis results viewer? I suspect that we've likely addressed this issue but let me know if you are still facing this problem. Thanks!
