### ISSUE TITLE
Non UTF-8 encoded files

### ISSUE THREAD

**Issue by anthonysena** [ohdsi-studies/Covid19CharacterizationCharybdis#47]
There are some files that are not UTF-8 Encoded in the package which appears to cause this issue:

![image](https://user-images.githubusercontent.com/12902366/85027404-e3bf9780-b147-11ea-9b20-9846e0cf4f44.png)

As a note: Git contains a handy utility for looking at the file encoding `E:\Program Files\G
it\usr\bin\file.exe * --mime-encoding` per this [SO article](https://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows)

**Comment by schuemie** [comment]
Perhaps related: There's the [findNonAsciiStringsInFolder function](http://ohdsi.github.io/OhdsiRTools/reference/findNonAsciiStringsInFolder.html) in OhdsiRTools for finding non-ASCII strings in your package..

**Comment by anthonysena** [comment]
Thanks @schuemie - that's good to know. I made use of the UTF8 R package for this issue https://cran.r-project.org/web/packages/utf8/index.html. I am going to close this out since best I can tell we've resolved the UTF-8 related issues.
