### ISSUE TITLE
Slow Execution of 201.sql

### ISSUE THREAD

**Issue by CartWill** [ohdsi-studies/Covid19CharacterizationCharybdis#49]
Hello,

I'm trying to run this and when I try to execute the runStudy function the execution gets stuck trying to run 201.sql.  The code is running but it's running for 3+ hours and finally times out.  It looks like the query in some places is trying to join measurement to measurement on person_id to determine a change in value which takes a really long time.  Other Sql platforms might optimize things by filtering the joins from the where clause BigQuery, our platform, seems to do things very literally. If I edit the query text to move some of the tables into cte expressions to filter them down before the join, is that OK? Here's an example of what I mean

Original (takes hours):
```
insert into  omop_covid19_cohort.e5avqxzfmeasurements
  --1.2 LOINC mg/dl
select m2.person_id,
       m2.measurement_id                   as event_id,
       m2.measurement_date                as start_date,
       DATE_ADD(IF(SAFE_CAST(m2.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m2.measurement_date  AS STRING)),SAFE_CAST(m2.measurement_date  AS DATE)), interval 1 DAY) as end_date,
       m2.measurement_concept_id          as target_concept_id,
       m2.visit_occurrence_id,
       m2.measurement_date                as sort_date
from omop_covid19.measurement m
       join omop_covid19.measurement m2
            on m.person_id = m2.person_id and DATE_DIFF(IF(SAFE_CAST(m2.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m2.measurement_date  AS STRING)),SAFE_CAST(m2.measurement_date  AS DATE)), IF(SAFE_CAST(m.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m.measurement_date  AS STRING)),SAFE_CAST(m.measurement_date  AS DATE)), DAY) between 0 and 2
       join omop_covid19_cohort.e5avqxzfcodesets codesets on (m.measurement_concept_id = codesets.concept_id and codesets.codeset_id = 7)
       join omop_covid19_cohort.e5avqxzfcodesets codesets2 on (m2.measurement_concept_id = codesets2.concept_id and codesets2.codeset_id = 7)
where m2.value_as_number > 0
  and m.value_as_number > 0
  and (m2.value_as_number - m.value_as_number) > 0.3
```

Modified (less than a minute):
```
insert into  omop_covid19_cohort.e5avqxzfmeasurements
  --1.2 LOINC mg/dl
with cte_measurements as (
   select * from omop_covid19.measurement m
   join omop_covid19_cohort.e5avqxzfcodesets codesets on (m.measurement_concept_id = codesets.concept_id and 
   codesets.codeset_id = 7)
   where m.value_as_number > 0
)
select m2.person_id,
       m2.measurement_id                   as event_id,
       m2.measurement_date                as start_date,
       DATE_ADD(IF(SAFE_CAST(m2.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m2.measurement_date  AS STRING)),SAFE_CAST(m2.measurement_date  AS DATE)), interval 1 DAY) as end_date,
       m2.measurement_concept_id          as target_concept_id,
       m2.visit_occurrence_id,
       m2.measurement_date                as sort_date
from cte_measurements m
       join omop_covid19.measurement m2
            on m.person_id = m2.person_id and DATE_DIFF(IF(SAFE_CAST(m2.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m2.measurement_date  AS STRING)),SAFE_CAST(m2.measurement_date  AS DATE)), IF(SAFE_CAST(m.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m.measurement_date  AS STRING)),SAFE_CAST(m.measurement_date  AS DATE)), DAY) between 0 and 2
       join omop_covid19_cohort.e5avqxzfcodesets codesets2 on (m2.measurement_concept_id = codesets2.concept_id and codesets2.codeset_id = 7)
where m2.value_as_number > 0
  and (m2.value_as_number - m.value_as_number) > 0.3
```

**Comment by anthonysena** [comment]
Hi @CartWill - generally speaking we want to keep the study code locked so users are only running the package vs. making modifications. Otherwise we run the risk of not being able to reproduce the results.

One question: does the cohort ever complete using the original code? The default behavior in this study package is to generate the cohorts 1 time and it will only generate the cohort if the SQL code changes. So, if cohort 201 did finish, it would by-pass that generation step again.

**Comment by CartWill** [comment]
No it did not finish.  I increased the timeout in the connection string but that did not help.

**Comment by kmkostka** [comment]
@anthonysena Cohort 201 (Acute Kidney Injury) was custom SQL not an ATLAS generated cohort. I'm open to a collaborator contributed optimization.

**Comment by anthonysena** [comment]
@kmkostka - good catch on the AKI definition! @CartWill - sorry if I gave the impression that we would not welcome a contribution around optimizing this cohort.

Looking at the SQL you provided: Using a CTE with an INSERT statement will not work across DBMS platforms unfortunately. One thought: could you put the results of the CTE into a TEMP table (call it #measurement_subset) and then use that for the remaining queries? Also, looking at the [code that populates the `#measurement` table](https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/master/inst/sql/sql_server/201.sql#L118-L257), we might be able to further optimize this for BigQuery by using a `UNION` to do a single insert into `#measurement` vs individual inserts. Let me know what you think and happy to collaborate on the code change if helpful.

**Comment by CartWill** [comment]
@anthonysena yeah that would probably work.  SqlRender and temp tables in BigQuery are messy so I try to avoid them if at all possible.

One thing that might work too is to just move the measurements into sub-queries where the filtering concepts are moved up into the sub query.  That's probably more compatible across partners than the cte.  Something like this:
```
insert into  omop_covid19_cohort.e5avqxzfmeasurements
  --1.2 LOINC mg/dl
select m2.person_id,
       m2.measurement_id                   as event_id,
       m2.measurement_date                as start_date,
       DATE_ADD(IF(SAFE_CAST(m2.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m2.measurement_date  AS STRING)),SAFE_CAST(m2.measurement_date  AS DATE)), interval 1 DAY) as end_date,
       m2.measurement_concept_id          as target_concept_id,
       m2.visit_occurrence_id,
       m2.measurement_date                as sort_date
from 
	( 
	  SELECT * 
	  FROM
		omop_covid19.measurement m
	  join omop_covid19_cohort.e5avqxzfcodesets codesets 
		on (m.measurement_concept_id = codesets.concept_id and codesets.codeset_id = 7) 
	) m
join (
	  SELECT * 
	  FROM 
		omop_covid19.measurement m2
	  join omop_covid19_cohort.e5avqxzfcodesets codesets2 
		on (m2.measurement_concept_id = codesets2.concept_id and codesets2.codeset_id = 7)
	) m2
            on m.person_id = m2.person_id and DATE_DIFF(IF(SAFE_CAST(m2.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m2.measurement_date  AS STRING)),SAFE_CAST(m2.measurement_date  AS DATE)), IF(SAFE_CAST(m.measurement_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(m.measurement_date  AS STRING)),SAFE_CAST(m.measurement_date  AS DATE)), DAY) between 0 and 2     
where m2.value_as_number > 0
  and m.value_as_number > 0
  and (m2.value_as_number - m.value_as_number) > 0.3
```

**Comment by anthonysena** [comment]
@CartWill sorry this issue has aged but it appears that you were able to resolve this issue.
