### ISSUE TITLE
ICD10 codes of influenza due to avian or novel H1N1 were missing in the concept set "Influenza conditions"

### ISSUE THREAD

**Issue by liyupeng111** [ohdsi-studies/Covid19CharacterizationCharybdis#53]
But relevant ICD9 codes were included.

![image](https://user-images.githubusercontent.com/2036673/85797002-df2b4e00-b708-11ea-8259-c713084808fe.png)

ICD10 | description
J09.01 | Influenza due to identified   avian influenza virus with respiratory manifestations
J09.010 | Influenza due to identified avian influenza virus with identified avian influenza pneumonia
J09.018 | Influenza due to identified avian influenza virus with other specified type of pneumonia
J09.019 | Influenza due to identified avian influenza virus with unspecified type of pneumonia
J09.02 | Influenza due to identified avian influenza virus with other respiratory manifestations
J09.03 | Influenza due to identified avian influenza virus with gastrointestinal manifestations
J09.090 | Influenza due to identified avian influenza virus with encephalopathy
J09.091 | Influenza due to identified avian influenza virus with myocarditis
J09.092 | Influenza due to identified avian influenza virus with otitis media
J09.098 | Influenza due to identified avian influenza virus with other manifestations
J09.11 | Influenza due to identified novel H1N1 influenza virus with respiratory manifestations
J09.110 | Influenza due to identified novel H1N1 influenza virus with identified novel H1N1 influenza pneumonia
J09.118 | Influenza due to identified novel H1N1 influenza virus with other specified type of pneumonia
J09.119 | Influenza due to identified novel H1N1 influenza virus with unspecified type of pneumonia
J09.12 | Influenza due to identified novel H1N1 influenza virus with other respiratory manifestations
J09.13 | Influenza due to identified novel H1N1 influenza virus with gastrointestinal manifestations
J09.190 | Influenza due to identified novel H1N1 influenza virus with encephalopathy
J09.191 | Influenza due to identified novel H1N1 influenza virus with myocarditis
J09.192 | Influenza due to identified novel H1N1 influenza virus with otitis media
J09.198 | Influenza due to identified novel H1N1 influenza virus with other manifestations

**Comment by kmkostka** [comment]
Unlike the [Hospitalization](https://github.com/ohdsi-studies/Covid19HospitalizationCharacterization) study, H1N1 flu is not a specific focus of this analysis. This study is using Flu year 2017-2018 as a comparator.

@pbr6cornell can review this suggestion when we do future Flu comparator cohorts.

**Comment by liyupeng111** [comment]
Thanks Kristin,
But ICD9 codes with avian and novel H1N1 flu were included. Should they be consistent?

**Comment by kmkostka** [comment]
That concept set/code list was originally constructed for a specific H1N1 comparator group (2009-2010 flu season) that was prior to ICD10 being used in the US. It’s difficult to add them now because we have already run the package on multiple sites. Only thing we can do is improve in future analyses.

**Comment by liyupeng111** [comment]
I finally figured out the reason. These ICD10 codes listed above became invalid a few years ago, and they are not in the recent version of ICD10.
Thanks!
