### ISSUE TITLE
CRAN versus GitHub Libraries - Discrepancies in DESCRIPTION file

### ISSUE THREAD

**Issue by kmkostka** [ohdsi-studies/Covid19CharacterizationCharybdis#54]
**Bug:** We have a reference in the DESCRIPTION file to
````
Remotes:
  OHDSI/CohortDiagnostics,
  OHDSI/FeatureExtraction,
  OHDSI/ParallelLogger,
  OHDSI/SqlRender,
  OHDSI/OhdsiSharing
````
First problem is that SqlRender is now in CRAN.

**Bug:** Second problem, our call to OHDSI/FeatureExtraction depends DatabaseConnector >= 3.0.0  is significantly higher than our version `Depends:   DatabaseConnector (>= 2.2.0)`. This can make `R` cranky. 
```
Error : package ‘DatabaseConnector’ 2.4.1 was found, but >= 3.0.0 is required by ‘FeatureExtraction’
````

**Underlying Issue:** The migration of [DatabaseConnector](https://github.com/ohdsi/DatabaseConnector) to [CRAN](https://cran.r-project.org/package=DatabaseConnector) and [SqlRender](https://github.com/ohdsi/SqlRender) to [CRAN](https://cran.r-project.org/package=SqlRender) is going to throw some errors during installation because of the mismatch in the library needed to load:

e.g.
````
devtools::install.github("ohdsi/DatabaseConnector")
````
vs
````
install.packages("DatabaseConnector")
````

**Enhancement:** We should help make this clearer to troubleshoot and we should update the DESCRIPTION to pull SqlRender from CRAN not OHDSI GitHub.

**Comment by anthonysena** [comment]
Agreed @kmkostka - I'm going to close this out since we can address this via the implementation of `renv` in the project per #73.
