### ISSUE TITLE
Inconsistent ICD9 and ICD10 codes for avian and novel H1N1 flu

### ISSUE THREAD

**Issue by liyupeng111** [ohdsi-studies/Covid19CharacterizationCharybdis#57]
This is the same issue reported here, https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/issues/53

Just want to rephase: the concept set definition included ICD9 codes with avian and novel H1N1 flu but not those ICD10 codes.

**Comment by kmkostka** [comment]
@pbr6cornell to adjudicate. We’ve already had multiple sites contribute results. We generally do not change the package once it’s been disseminated even if there are later identified design issues. We would have to acknowledge these in the discussion sections of subsequent manuscripts.
