### ISSUE TITLE
JSON files for cohort definitions display long CONCEPT_IDs in scientific notation

### ISSUE THREAD

**Issue by jatjasonthomas** [ohdsi-studies/Covid19CharacterizationCharybdis#68]
See https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/master/inst/cohorts/129.json as an example.

Maybe we should change the CONCEPT_ID to a string type like CONCEPT_CODE (which doesn't have this issue) to avoid this happening. Currently, users have to search for the CONCEPT_CODE within their vocabulary to verify the CONCEPT_ID value shown in the JSON file. Many of my personal queries solely use CONCEPT_IDs rather than CONCEPT_CODEs, so this adds a lot of overhead when I compare my query's concept set against the existing OHDSI concept sets.

**Comment by anthonysena** [comment]
@jatjasonthomas thanks for raising this issue. I think this is a by-product of the way we're serializing the JSON to a file as I'm certain that the concept ID's are not masked this way via WebAPI.

> Currently, users have to search for the CONCEPT_CODE within their vocabulary to verify the CONCEPT_ID value shown in the JSON file.

It sounds like you (and your team) are using the JSON files to do some quality control on the cohorts and how they work in your database. Do I have this right? Just curious as perhaps there is an opportunity to make this process easier as it sounds like it would be a potential addition to the [Cohort Diagnostics](https://github.com/OHDSI/CohortDiagnostics) package.

**Comment by jatjasonthomas** [comment]
@anthonysena Yes - I'm using the JSON files to do some quality control on the cohorts and how they work in my database. The JSON files are a faster way to see the concept sets used for each cohort opposed to the ATLAS link (in large part due to the current need to login to ATLAS, then re-paste the link a second time).

Additionally, I'm using them as documentation in other work I'm doing so that others can easily see the concept sets I used for analyses. For example, I'm generating COVID-19 epi curves for my institution. I select patients by querying the OHDSI cohort tables produced by CHARYBDIS to count cases, total tests, deaths, hospitalizations, etc. over time. In my codes' documentation, I point to the  JSON files listed above for each cohort.

It's not a huge issue since ATLAS suffices, but the convenience of using the JSON files in this manner is hampered by the CONCEPT_IDs being displayed in scientific notation. For now I will likely use the ATLAS links instead.

**Comment by anthonysena** [comment]
@jatjasonthomas thanks for sharing those details and glad that you are able to use ATLAS since the JSON has this limitation. I've opened an issue to aim to resolve this elsewhere so that we don't face this problem again. Thanks!
