### ISSUE TITLE
Problems running Covid19CharacterizationCharybdis

### ISSUE THREAD

**Issue by alabarga** [ohdsi-studies/Covid19CharacterizationCharybdis#79]
We have tried to run Covid19CharacterizationCharybdis on our data, and have experienced several issues:

- runCohortDiagnostics runs very slow, with some cohorts taking about 15 hours to complete 
- although runCohortDiagnostics generate results, and stagingCohortTable has values, cohortTable is empty, so 

```
  counts <- getCohortCounts(connection = connection,
                            cohortDatabaseSchema = cohortDatabaseSchema,
                            cohortTable = cohortTable)
```
  
is empty

```
  writeToCsv(counts, file.path(exportFolder, "cohort_count.csv"), incremental = incremental, cohortId = counts$cohortId)
```  
writes no file, and

``` 
  counts <- readr::read_csv(file.path(exportFolder, "cohort_count.csv"), col_types = readr::cols())
``` 

causes a `file not found` error

we are running 

- Postgres 11
- R version 4.0.3 (2020-10-10)
- Covid19CharacterizationCharybdis (1.4.0)
- DatabaseConnector (3.0.0)

any ideas?

**Comment by anthonysena** [comment]
Hi there - a few comments & questions:

> runCohortDiagnostics runs very slow, with some cohorts taking about 15 hours to complete

It would be helpful to see the logs from your run (I can contact you via email to share this) and we can see which cohorts are taking the most time. One thing that has been noted by others who have run this package: some of the cohorts in this study are using the `measurement.value_as_concept_id` and may require an additional index.

> although runCohortDiagnostics generate results, and stagingCohortTable has values, cohortTable is empty, so...

Agreed - this seems odd and problematic. Hoping that viewing the logs can help to provide clues on what is happening
