### ISSUE TITLE
Scientific notation in JSON files causing issue during import

### ISSUE THREAD

**Issue by kmkostka** [ohdsi-studies/Covid19CharacterizationCharybdis#80]
https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/3d66b7b2b113c4513d9a590ea7cd296a3fc41d96/inst/cohorts/114.json#L121

My team found some JSONs contain scientific notation instead of the fully specified concept ID. This is causing an issue in important where ATLAS is rendering random concept sets because it doesn't handle scientific notation.

@anthonysena @pbr6cornell this might be upstream of this package but it's something we should investigate and resolve.

**Comment by anthonysena** [comment]
Hey @kmkostka - thanks for noting this. Yes, this is an issue that we traced back to ROhdsiWebApi which has since been resolved. 

Just let me know the impact this has as pulling down the JSON may be a manual exercise since I'd want to obtain these from the locked versions on atlas.ohdsi.org.

**Comment by kmkostka** [comment]
I haven't looked at the number of JSONs this shows up. It seems like something we should fix for the longevity of reuse of these artifacts for future work given how many citations point to this repo.

**Comment by anthonysena** [comment]
Agreed - I'll work to get this resolved

**Comment by anthonysena** [comment]
@kmkostka v1.4.1 of this package contains updated cohort JSON that remove the scientific notation. Thanks!
