### ISSUE TITLE
Concept code 1240581000000104 maps to wrong concept id in cohort JSON

### ISSUE THREAD

**Issue by ellisille** [ohdsi-studies/Covid19CharacterizationCharybdis#81]
I'm not sure, if this related to the reported scientific notation issue https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/issues/68.

In cohorts 126-141 there is a concept 
> "concept" : {
> 	"CONCEPT_ID" : 3.731028e+07,
> 	"CONCEPT_NAME" : "2019 novel coronavirus detected",
> 	"STANDARD_CONCEPT" : "N",
> 	"STANDARD_CONCEPT_CAPTION" : "Non-Standard",
> 	"INVALID_REASON" : "V",
> 	"INVALID_REASON_CAPTION" : "Valid",
> 	"CONCEPT_CODE" : "1240581000000104",
> 	"DOMAIN_ID" : "Measurement",
> 	"VOCABULARY_ID" : "SNOMED",
> 	"CONCEPT_CLASS_ID" : "Clinical Finding"
> },

When importing these cohorts in Atlas, the concept ID is mapped to 37310280, which is actually the concept "High priority for SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) vaccination" not "2019 novel coronavirus detected". The correct concept ID would be 37310282.

Similar issue is with 
> "concept" : {
> 	"CONCEPT_ID" : 3.731028e+07,
> 	"CONCEPT_NAME" : "2019 novel coronavirus not detected",
> 	"STANDARD_CONCEPT" : "N",
> 	"STANDARD_CONCEPT_CAPTION" : "Non-Standard",
> 	"INVALID_REASON" : "V",
> 	"INVALID_REASON_CAPTION" : "Valid",
> 	"CONCEPT_CODE" : "1240591000000102",
> 	"DOMAIN_ID" : "Measurement",
> 	"VOCABULARY_ID" : "SNOMED",
> 	"CONCEPT_CLASS_ID" : "Clinical Finding"
> },

**Comment by anthonysena** [comment]
Hi @ellisille - you have it right. This is the same issue as described in #68. I'll keep this issue open and close it out when I've updated the JSON accordingly. Thanks!

**Comment by anthonysena** [comment]
I've updated the JSON to fix this issue. v1.4.1 of the package will contain this fix. Thanks!
